YouTube video page
elasfarc/Youtube-clone pull request #1
Opened 2020-07-14 02:44 UTC by elasfarc

# Youtube Clone 
An HTML document that matches the appearance of  a YouTube video page.

![WhatsApp Image 2020-07-14 at 4 11 17 AM](https://user-images.githubusercontent.com/63879921/87375444-84f50e80-c58b-11ea-8df4-4ca0879b4e2b.jpeg)

2020-07-14 03:21 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## What a remarkable project you have built 💯! This is impressive 🤩👌🧨!

### But in order to get it approved, we need to work on some changes. Let's see...

- Let's make the README more professional. Right now it's looking bland. Remember, READMEs are very important part of a project. It provides valuable information about the project. You can use this README template: https://github.com/microverseinc/readme-template. Fill up the sections that are necessary for your project and remove the other sections. For eg., `Install`, `Usage`, `Run tests` and `Deployment` is irrelevant to your project, so you can remove them.

- Remember to `.gitignore` the files that are irrelevant to your project. Please add a `.gitignore` file and put the `.DS Store` file in that. Also, this file is present in the assets folder. Be sure to remove all of them.
![image](https://user-images.githubusercontent.com/57726348/87379613-4e7cbb00-c5ae-11ea-8651-a6375f35fd85.png)

- There are lots of errors and warnings in your HTML file. Please go over to https://validator.w3.org/#validate_by_input and paste your HTML code. Go through the errors and warnings and fix them.

![image](https://user-images.githubusercontent.com/57726348/87379859-d6fb5b80-c5ae-11ea-9690-2733b3fb1af4.png)

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻

2020-07-14 17:35 UTC, bertil291utn commented on homepage.css
> +}
Comments: It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history (screenshot from Pathwright)
❌ **commented piece of codes** `/* .nav { color: red;} */`
✔ **comments about code** `/*Navigation */`
Comments about the code is okay and should only be tagged as OPTIONAL if it's unnecessary and please provide details why it is unnecessary.

2020-07-14 17:35 UTC, bertil291utn commented on homepage.html
> +          <li><hr id="previewContainer-hLine"/></li>
## Using an ID Selector for Multiple Elements[1]
When writing CSS, there should only be one ID in the HTML. Always use the class attribute for multiple elements.
- [ ] Use `class` instead `id`

_[1] [Good and Bad CSS practices](https://speckyboy.com/good-bad-css-practices/)_

2020-07-14 17:35 UTC, bertil291utn commented on homepage.html
> +       <section class="menu-logo">
## Check usage of semantic HTML elements. 
Section tag need a h2-h6 tag to accomplish. Check html [validator](https://validator.w3.org/#validate-by-input)

2020-07-14 17:38 UTC, bertil291utn commented
**Status:** Changes requested 🔴  :shipit: ? Not yet

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

Your work is terrific you certainly put all your effort in this project, however, we need to make some changes.

- [ ] Improve your README file. Try to follow this [template](https://github.com/microverseinc/readme-template)
- [ ] Your pull request comment should not be a copy-paste of your README file, please edit your pull request. Pull Request has meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

![image](https://user-images.githubusercontent.com/24902525/87455859-b2fa4300-c5cb-11ea-8663-16cd1b04270c.png)

- [ ] Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

- [ ] Please work also with inline comments on this Pull request
<hr>


Guys work in the requested changes above and request code for another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-15 03:31 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Great job guys :+1: you have made a great youtube clone but you still need to fix one final think before your project gets approved :checkered_flag: .

- [ ] I still see that you still have the DS_Store file in your repository, please remove it I understand that you have added it to the .gitignore but you need to remove it first and push. then add the .gitignore file again.
![image](https://user-images.githubusercontent.com/34653764/87500336-1a5bd580-c654-11ea-9770-b26278a3d3e0.png)


### Please make all the required changes before you submit another code review.
## Happy Coding :tophat: 
_If you have any issue or need help don't hesitate to contact me on slack_

2020-07-15 15:35 UTC, bertil291utn commented
**Status:** Approved ✅

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

 ## Ship it

<img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="100" />

Please merge to master branch and move on with the next assignment.

You're doing  a great job keep going 💻 🚀 🔥

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-16 03:08 UTC, merged